export const API_BASE_URL = 'https://castglo.onrender.com/api/v1'

export const API_ENDPOINTS = {
  ADMIN: {
    USERS: '/admin/users',
    SUSPEND_USER: (userId: string) => `/admin/users/${userId}/suspend`,
    UNSUSPEND_USER: (userId: string) => `/admin/users/${userId}/unsuspend`,
    VERIFY_USER: (userId: string) => `/admin/users/${userId}/verify`,
    DELETE_USER: (userId: string) => `/admin/users/${userId}`,
    ACTION_LOGS: '/admin/action-logs',
    ANALYTICS: '/admin/analytics',
    LEADS: '/admin/leads',
    SUBSCRIPTIONS: '/admin/subscriptions',
  },
  APPLICATIONS: {
    CREATE: '/applications',
    ME: '/applications/me',
    BY_CASTING_CALL: (castingCallId: string) => `/applications/${castingCallId}`,
    DETAILS: (applicationId: string) => `/applications/details/${applicationId}`,
    SHORTLIST: (applicationId: string) => `/applications/${applicationId}/shortlist`,
    REJECT: (applicationId: string) => `/applications/${applicationId}/reject`,
    ACCEPT: (applicationId: string) => `/applications/${applicationId}/accept`,
    COMMUNICATION: (applicationId: string) => `/applications/${applicationId}/communication`,
    WITHDRAW: (applicationId: string) => `/applications/${applicationId}`,
  },
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    VERIFY_EMAIL: '/auth/verify-email',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    CHANGE_PASSWORD: '/auth/change-password',
    ME: '/auth/me',
  },
  CASTING_CALLS: {
    GET_ALL: '/casting-calls',
    CREATE: '/casting-calls',
    MY_LISTINGS: '/casting-calls/user/my-listings',
    GET_ONE: (id: string) => `/casting-calls/${id}`,
    UPDATE: (id: string) => `/casting-calls/${id}`,
    DELETE: (id: string) => `/casting-calls/${id}`,
    CLOSE: (id: string) => `/casting-calls/${id}/close`,
  },
  LEADS: {
    CREATE: '/leads',
    ADMIN_GET_ALL: '/leads/admin/leads',
    ADMIN_GET_ONE: (id: string) => `/leads/admin/leads/${id}`,
    ADMIN_DELETE: (id: string) => `/leads/admin/leads/${id}`,
    ADMIN_CONVERT: (id: string) => `/leads/admin/leads/${id}/convert`,
  },
  PROFILES: {
    CREATE: '/profiles',
    ME: '/profiles/me',
    UPDATE_ME: '/profiles/me',
    ADD_HEADSHOT: '/profiles/me/headshots',
    DELETE_HEADSHOT: (headshotId: string) => `/profiles/me/headshots/${headshotId}`,
    UPLOAD_SHOWREEL: '/profiles/me/showreel',
    SEARCH: '/profiles/search',
    GET_ONE: (userId: string) => `/profiles/${userId}`,
  },
  SUBSCRIPTIONS: {
    CREATE_CHECKOUT_SESSION: '/subscriptions/create-checkout-session',
    STATUS: '/subscriptions/status',
    DETAILS: '/subscriptions/details',
    UPGRADE: '/subscriptions/upgrade',
    CANCEL: '/subscriptions/cancel',
    WEBHOOK: '/subscriptions/webhook',
    PLANS: '/subscriptions/plans',
  },
  USERS: {
    PROFILE: '/users/profile',
    UPDATE_PROFILE: '/users/profile',
    UPDATE_PROFILE_PICTURE: '/users/profile-picture',
    DELETE_ACCOUNT: '/users/account',
    SEARCH: '/users/search',
    GET_ONE: (userId: string) => `/users/${userId}`,
  },
}
