export const countryToTimeZoneHint: Record<string, string[]> = {
  "United Kingdom": ["Europe/London", "GMT"],
  "United States": ["America/New_York", "America/Chicago", "America/Denver", "America/Los_Angeles", "America/Anchorage", "Pacific/Honolulu"],
  "Canada": ["America/Toronto", "America/Vancouver", "America/Edmonton", "America/Winnipeg", "America/Halifax", "America/St_Johns"],
  "France": ["Europe/Paris"],
  "Germany": ["Europe/Berlin"],
  "Netherlands": ["Europe/Amsterdam"],
  "Belgium": ["Europe/Brussels"],
  "Spain": ["Europe/Madrid"],
  "Portugal": ["Europe/Lisbon"],
  "Italy": ["Europe/Rome"],
  "Sweden": ["Europe/Stockholm"],
  "Norway": ["Europe/Oslo"],
  "Denmark": ["Europe/Copenhagen"],
  "Finland": ["Europe/Helsinki"],
  "Poland": ["Europe/Warsaw"],
  "Romania": ["Europe/Bucharest"],
  "Ukraine": ["Europe/Kiev"],
  "Turkey": ["Europe/Istanbul"],
  "Greece": ["Europe/Athens"],
  "Ireland": ["Europe/Dublin"],
  "Scotland": ["Europe/London"], // Close enough
  "Wales": ["Europe/London"], // Close enough
  "India": ["Asia/Kolkata"],
  "Pakistan": ["Asia/Karachi"],
  "Bangladesh": ["Asia/Dhaka"],
  "Sri Lanka": ["Asia/Colombo"],
  "Nepal": ["Asia/Kathmandu"],
  "China": ["Asia/Shanghai", "Asia/Chongqing", "Asia/Harbin", "Asia/Urumqi"],
  "Japan": ["Asia/Tokyo"],
  "South Korea": ["Asia/Seoul"],
  "Indonesia": ["Asia/Jakarta", "Asia/Makassar", "Asia/Jayapura"],
  "Malaysia": ["Asia/Kuala_Lumpur"],
  "Singapore": ["Asia/Singapore"],
  "Philippines": ["Asia/Manila"],
  "Thailand": ["Asia/Bangkok"],
  "Vietnam": ["Asia/Ho_Chi_Minh"],
  "Australia": ["Australia/Sydney", "Australia/Melbourne", "Australia/Brisbane", "Australia/Perth", "Australia/Adelaide", "Australia/Darwin", "Australia/Hobart"],
  "New Zealand": ["Pacific/Auckland"],
  "Brazil": ["America/Sao_Paulo", "America/Manaus", "America/Belem", "America/Fortaleza"],
  "Mexico": ["America/Mexico_City", "America/Monterrey", "America/Tijuana"],
  "Argentina": ["America/Argentina/Buenos_Aires"],
  "Jamaica": ["America/Jamaica"],
  "Trinidad and Tobago": ["America/Port_of_Spain"],
  "United Arab Emirates": ["Asia/Dubai"],
  "Saudi Arabia": ["Asia/Riyadh"],
  "Qatar": ["Asia/Qatar"],
  "Israel": ["Asia/Jerusalem"],
  "Russia": ["Europe/Moscow", "Asia/Yekaterinburg", "Asia/Novosibirsk", "Asia/Vladivostok"],
};

export function detectCountry() {
  // The platform is standardized to "United Kingdom First". 
  // We default to United Kingdom regardless of the user's current location to ensure consistency.
  return "United Kingdom";
}
