export interface ReferenceItem {
  code: string;
  label: string;
  group: string;
  sortOrder: number;
  iso6391?: string | null;
  countryFocus?: string;
}

export const OPPORTUNITIES_SOUGHT_OPTIONS = [
  "Film",
  "TV",
  "Theatre",
  "Commercials",
  "Voiceover",
  "Modelling",
  "Live Events",
  "Brand Collaborations",
  "Content Creation",
  "Music Videos",
];

export const MUSIC_GENRES: ReferenceItem[] = [
  { code: "pop", label: "Pop", group: "Mainstream / Popular", sortOrder: 1 },
  { code: "afrobeats", label: "Afrobeats", group: "Mainstream / Popular", sortOrder: 2 },
  { code: "afro_pop", label: "Afro Pop", group: "Mainstream / Popular", sortOrder: 3 },
  { code: "rnb", label: "R&B", group: "Mainstream / Popular", sortOrder: 4 },
  { code: "soul", label: "Soul", group: "Mainstream / Popular", sortOrder: 5 },
  { code: "hip_hop", label: "Hip Hop", group: "Mainstream / Popular", sortOrder: 6 },
  { code: "rap", label: "Rap", group: "Mainstream / Popular", sortOrder: 7 },
  { code: "trap", label: "Trap", group: "Mainstream / Popular", sortOrder: 8 },
  { code: "dancehall", label: "Dancehall", group: "Mainstream / Popular", sortOrder: 9 },
  { code: "reggae", label: "Reggae", group: "Mainstream / Popular", sortOrder: 10 },
  { code: "amapiano", label: "Amapiano", group: "Mainstream / Popular", sortOrder: 11 },
  { code: "house", label: "House", group: "Mainstream / Popular", sortOrder: 12 },
  { code: "edm", label: "EDM", group: "Mainstream / Popular", sortOrder: 13 },
  { code: "electronic", label: "Electronic", group: "Mainstream / Popular", sortOrder: 14 },
  { code: "drum_and_bass", label: "Drum & Bass", group: "Mainstream / Popular", sortOrder: 15 },
  { code: "garage", label: "Garage", group: "Mainstream / Popular", sortOrder: 16 },
  { code: "uk_garage", label: "UK Garage", group: "Mainstream / Popular", sortOrder: 17 },
  { code: "grime", label: "Grime", group: "Mainstream / Popular", sortOrder: 18 },
  { code: "classical", label: "Classical", group: "Traditional / Classic", sortOrder: 19 },
  { code: "opera", label: "Opera", group: "Traditional / Classic", sortOrder: 20 },
  { code: "jazz", label: "Jazz", group: "Traditional / Classic", sortOrder: 21 },
  { code: "blues", label: "Blues", group: "Traditional / Classic", sortOrder: 22 },
  { code: "gospel", label: "Gospel", group: "Faith / Inspirational", sortOrder: 23 },
  { code: "contemporary_gospel", label: "Contemporary Gospel", group: "Faith / Inspirational", sortOrder: 24 },
  { code: "worship", label: "Worship", group: "Faith / Inspirational", sortOrder: 25 },
  { code: "hymns", label: "Hymns", group: "Faith / Inspirational", sortOrder: 26 },
  { code: "christian_contemporary", label: "Christian Contemporary", group: "Faith / Inspirational", sortOrder: 27 },
  { code: "praise", label: "Praise", group: "Faith / Inspirational", sortOrder: 28 },
  { code: "gospel_choir", label: "Gospel Choir", group: "Faith / Inspirational", sortOrder: 29 },
  { code: "inspirational", label: "Inspirational", group: "Faith / Inspirational", sortOrder: 30 },
  { code: "folk", label: "Folk", group: "Traditional / Classic", sortOrder: 31 },
  { code: "country", label: "Country", group: "Traditional / Classic", sortOrder: 32 },
  { code: "bluegrass", label: "Bluegrass", group: "Traditional / Classic", sortOrder: 33 },
  { code: "rock", label: "Rock", group: "Rock / Alternative", sortOrder: 34 },
  { code: "pop_rock", label: "Pop Rock", group: "Rock / Alternative", sortOrder: 35 },
  { code: "alternative_rock", label: "Alternative Rock", group: "Rock / Alternative", sortOrder: 36 },
  { code: "indie_rock", label: "Indie Rock", group: "Rock / Alternative", sortOrder: 37 },
  { code: "indie_pop", label: "Indie Pop", group: "Rock / Alternative", sortOrder: 38 },
  { code: "punk", label: "Punk", group: "Rock / Alternative", sortOrder: 39 },
  { code: "metal", label: "Metal", group: "Rock / Alternative", sortOrder: 40 },
  { code: "soft_rock", label: "Soft Rock", group: "Rock / Alternative", sortOrder: 41 },
  { code: "highlife", label: "Highlife", group: "African / World / Cultural", sortOrder: 42 },
  { code: "fuji", label: "Fuji", group: "African / World / Cultural", sortOrder: 43 },
  { code: "juju", label: "Juju", group: "African / World / Cultural", sortOrder: 44 },
  { code: "apala", label: "Apala", group: "African / World / Cultural", sortOrder: 45 },
  { code: "afro_fusion", label: "Afro Fusion", group: "African / World / Cultural", sortOrder: 46 },
  { code: "afro_soul", label: "Afro Soul", group: "African / World / Cultural", sortOrder: 47 },
  { code: "afro_jazz", label: "Afro Jazz", group: "African / World / Cultural", sortOrder: 48 },
  { code: "world_music", label: "World Music", group: "African / World / Cultural", sortOrder: 49 },
  { code: "traditional_cultural", label: "Traditional / Cultural", group: "African / World / Cultural", sortOrder: 50 },
  { code: "latin", label: "Latin", group: "Latin / Global", sortOrder: 51 },
  { code: "salsa", label: "Salsa", group: "Latin / Global", sortOrder: 52 },
  { code: "reggaeton", label: "Reggaeton", group: "Latin / Global", sortOrder: 53 },
  { code: "bachata", label: "Bachata", group: "Latin / Global", sortOrder: 54 },
  { code: "samba", label: "Samba", group: "Latin / Global", sortOrder: 55 },
  { code: "bossa_nova", label: "Bossa Nova", group: "Latin / Global", sortOrder: 56 },
  { code: "musical_theatre", label: "Musical Theatre", group: "Performance / Screen / Theatre", sortOrder: 57 },
  { code: "soundtrack_film_music", label: "Soundtrack / Film Music", group: "Performance / Screen / Theatre", sortOrder: 58 },
  { code: "spoken_word", label: "Spoken Word", group: "Performance / Screen / Theatre", sortOrder: 59 },
  { code: "childrens_music", label: "Children's Music", group: "Performance / Screen / Theatre", sortOrder: 60 },
  { code: "lo_fi", label: "Lo-fi", group: "Chill / Lifestyle / Modern", sortOrder: 61 },
  { code: "acoustic", label: "Acoustic", group: "Chill / Lifestyle / Modern", sortOrder: 62 },
  { code: "easy_listening", label: "Easy Listening", group: "Chill / Lifestyle / Modern", sortOrder: 63 },
  { code: "chillout", label: "Chillout", group: "Chill / Lifestyle / Modern", sortOrder: 64 },
  { code: "ambient", label: "Ambient", group: "Chill / Lifestyle / Modern", sortOrder: 65 },
  { code: "neo_soul", label: "Neo Soul", group: "Chill / Lifestyle / Modern", sortOrder: 66 },
  { code: "funk", label: "Funk", group: "Chill / Lifestyle / Modern", sortOrder: 67 },
  { code: "disco", label: "Disco", group: "Chill / Lifestyle / Modern", sortOrder: 68 },
  { code: "experimental", label: "Experimental", group: "Other / Specialist", sortOrder: 69 },
  { code: "instrumental", label: "Instrumental", group: "Other / Specialist", sortOrder: 70 },
  { code: "fusion", label: "Fusion", group: "Other / Specialist", sortOrder: 71 },
  { code: "cross_genre", label: "Cross-Genre", group: "Other / Specialist", sortOrder: 72 },
  { code: "other", label: "Other", group: "Other / Specialist", sortOrder: 73 },
];
export const LANGUAGES: ReferenceItem[] = [
  { code: "english", label: "English", group: "International / Major", iso6391: "en", sortOrder: 1 },
  { code: "french", label: "French", group: "International / Major", iso6391: "fr", sortOrder: 2 },
  { code: "spanish", label: "Spanish", group: "International / Major", iso6391: "es", sortOrder: 3 },
  { code: "portuguese", label: "Portuguese", group: "International / Major", iso6391: "pt", sortOrder: 4 },
  { code: "german", label: "German", group: "International / Major", iso6391: "de", sortOrder: 5 },
  { code: "italian", label: "Italian", group: "International / Major", iso6391: "it", sortOrder: 6 },
  { code: "dutch", label: "Dutch", group: "International / Major", iso6391: "nl", sortOrder: 7 },
  { code: "arabic", label: "Arabic", group: "International / Major", iso6391: "ar", sortOrder: 8 },
  { code: "mandarin_chinese", label: "Mandarin Chinese", group: "International / Major", iso6391: "zh", sortOrder: 9 },
  { code: "cantonese", label: "Cantonese", group: "International / Major", iso6391: null, sortOrder: 10 },
  { code: "japanese", label: "Japanese", group: "International / Major", iso6391: "ja", sortOrder: 11 },
  { code: "korean", label: "Korean", group: "International / Major", iso6391: "ko", sortOrder: 12 },
  { code: "hindi", label: "Hindi", group: "International / Major", iso6391: "hi", sortOrder: 13 },
  { code: "urdu", label: "Urdu", group: "International / Major", iso6391: "ur", sortOrder: 14 },
  { code: "russian", label: "Russian", group: "International / Major", iso6391: "ru", sortOrder: 15 },
  { code: "ukrainian", label: "Ukrainian", group: "International / Major", iso6391: "uk", sortOrder: 16 },
  { code: "turkish", label: "Turkish", group: "International / Major", iso6391: "tr", sortOrder: 17 },
  { code: "greek", label: "Greek", group: "International / Major", iso6391: "el", sortOrder: 18 },
  { code: "swedish", label: "Swedish", group: "European", iso6391: "sv", sortOrder: 19 },
  { code: "norwegian", label: "Norwegian", group: "European", iso6391: "no", sortOrder: 20 },
  { code: "danish", label: "Danish", group: "European", iso6391: "da", sortOrder: 21 },
  { code: "finnish", label: "Finnish", group: "European", iso6391: "fi", sortOrder: 22 },
  { code: "polish", label: "Polish", group: "European", iso6391: "pl", sortOrder: 23 },
  { code: "romanian", label: "Romanian", group: "European", iso6391: "ro", sortOrder: 24 },
  { code: "hungarian", label: "Hungarian", group: "European", iso6391: "hu", sortOrder: 25 },
  { code: "czech", label: "Czech", group: "European", iso6391: "cs", sortOrder: 26 },
  { code: "slovak", label: "Slovak", group: "European", iso6391: "sk", sortOrder: 27 },
  { code: "bulgarian", label: "Bulgarian", group: "European", iso6391: "bg", sortOrder: 28 },
  { code: "croatian", label: "Croatian", group: "European", iso6391: "hr", sortOrder: 29 },
  { code: "serbian", label: "Serbian", group: "European", iso6391: "sr", sortOrder: 30 },
  { code: "slovenian", label: "Slovenian", group: "European", iso6391: "sl", sortOrder: 31 },
  { code: "albanian", label: "Albanian", group: "European", iso6391: "sq", sortOrder: 32 },
  { code: "lithuanian", label: "Lithuanian", group: "European", iso6391: "lt", sortOrder: 33 },
  { code: "latvian", label: "Latvian", group: "European", iso6391: "lv", sortOrder: 34 },
  { code: "estonian", label: "Estonian", group: "European", iso6391: "et", sortOrder: 35 },
  { code: "hebrew", label: "Hebrew", group: "Middle East / Africa", iso6391: "he", sortOrder: 36 },
  { code: "persian_farsi", label: "Persian / Farsi", group: "Middle East / Africa", iso6391: "fa", sortOrder: 37 },
  { code: "amharic", label: "Amharic", group: "Middle East / Africa", iso6391: "am", sortOrder: 38 },
  { code: "swahili", label: "Swahili", group: "African", iso6391: "sw", sortOrder: 39 },
  { code: "hausa", label: "Hausa", group: "African", iso6391: null, sortOrder: 40 },
  { code: "yoruba", label: "Yoruba", group: "African", iso6391: null, sortOrder: 41 },
  { code: "igbo", label: "Igbo", group: "African", iso6391: null, sortOrder: 42 },
  { code: "pidgin_english", label: "Pidgin English", group: "African", iso6391: null, sortOrder: 43 },
  { code: "zulu", label: "Zulu", group: "African", iso6391: "zu", sortOrder: 44 },
  { code: "xhosa", label: "Xhosa", group: "African", iso6391: "xh", sortOrder: 45 },
  { code: "afrikaans", label: "Afrikaans", group: "African", iso6391: "af", sortOrder: 46 },
  { code: "twi", label: "Twi", group: "African", iso6391: null, sortOrder: 47 },
  { code: "ga", label: "Ga", group: "African", iso6391: null, sortOrder: 48 },
  { code: "edo", label: "Edo", group: "African", iso6391: null, sortOrder: 49 },
  { code: "efik", label: "Efik", group: "African", iso6391: null, sortOrder: 50 },
  { code: "ibibio", label: "Ibibio", group: "African", iso6391: null, sortOrder: 51 },
  { code: "bengali", label: "Bengali", group: "South Asian", iso6391: "bn", sortOrder: 52 },
  { code: "punjabi", label: "Punjabi", group: "South Asian", iso6391: "pa", sortOrder: 53 },
  { code: "tamil", label: "Tamil", group: "South Asian", iso6391: "ta", sortOrder: 54 },
  { code: "telugu", label: "Telugu", group: "South Asian", iso6391: "te", sortOrder: 55 },
  { code: "malayalam", label: "Malayalam", group: "South Asian", iso6391: "ml", sortOrder: 56 },
  { code: "gujarati", label: "Gujarati", group: "South Asian", iso6391: "gu", sortOrder: 57 },
  { code: "marathi", label: "Marathi", group: "South Asian", iso6391: "mr", sortOrder: 58 },
  { code: "nepali", label: "Nepali", group: "South Asian", iso6391: "ne", sortOrder: 59 },
  { code: "sinhala", label: "Sinhala", group: "South Asian", iso6391: "si", sortOrder: 60 },
  { code: "thai", label: "Thai", group: "Southeast Asian", iso6391: "th", sortOrder: 61 },
  { code: "vietnamese", label: "Vietnamese", group: "Southeast Asian", iso6391: "vi", sortOrder: 62 },
  { code: "indonesian", label: "Indonesian", group: "Southeast Asian", iso6391: "id", sortOrder: 63 },
  { code: "malay", label: "Malay", group: "Southeast Asian", iso6391: "ms", sortOrder: 64 },
  { code: "tagalog", label: "Tagalog", group: "Southeast Asian", iso6391: "tl", sortOrder: 65 },
  { code: "filipino", label: "Filipino", group: "Southeast Asian", iso6391: null, sortOrder: 66 },
  { code: "burmese", label: "Burmese", group: "Southeast Asian", iso6391: "my", sortOrder: 67 },
  { code: "khmer", label: "Khmer", group: "Southeast Asian", iso6391: "km", sortOrder: 68 },
  { code: "lao", label: "Lao", group: "Southeast Asian", iso6391: "lo", sortOrder: 69 },
  { code: "somali", label: "Somali", group: "African", iso6391: "so", sortOrder: 70 },
  { code: "wolof", label: "Wolof", group: "African", iso6391: null, sortOrder: 71 },
  { code: "lingala", label: "Lingala", group: "African", iso6391: null, sortOrder: 72 },
  { code: "kinyarwanda", label: "Kinyarwanda", group: "African", iso6391: "rw", sortOrder: 73 },
  { code: "luganda", label: "Luganda", group: "African", iso6391: "lg", sortOrder: 74 },
  { code: "shona", label: "Shona", group: "African", iso6391: "sn", sortOrder: 75 },
  { code: "other", label: "Other", group: "Other", iso6391: null, sortOrder: 76 },
];
export const ACCENTS: ReferenceItem[] = [
  { code: "british_rp", label: "British RP / Received Pronunciation", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 1 },
  { code: "standard_british", label: "Standard British", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 2 },
  { code: "london", label: "London", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 3 },
  { code: "cockney", label: "Cockney", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 4 },
  { code: "essex", label: "Essex", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 5 },
  { code: "estuary_english", label: "Estuary English", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 6 },
  { code: "multicutural_london_english", label: "Multicultural London English", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 7 },
  { code: "southern_english", label: "Southern English", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 8 },
  { code: "northern_english", label: "Northern English", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 9 },
  { code: "yorkshire", label: "Yorkshire", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 10 },
  { code: "lancashire", label: "Lancashire", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 11 },
  { code: "geordie", label: "Geordie", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 12 },
  { code: "scouse", label: "Scouse", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 13 },
  { code: "mancunian", label: "Mancunian", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 14 },
  { code: "west_midlands", label: "West Midlands", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 15 },
  { code: "birmingham_brummie", label: "Birmingham / Brummie", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 16 },
  { code: "east_midlands", label: "East Midlands", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 17 },
  { code: "west_country", label: "West Country", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 18 },
  { code: "welsh", label: "Welsh", group: "UK & Ireland", countryFocus: "Wales", sortOrder: 19 },
  { code: "cardiff", label: "Cardiff / South Welsh", group: "UK & Ireland", countryFocus: "Wales", sortOrder: 20 },
  { code: "valleys_welsh", label: "Valleys Welsh", group: "UK & Ireland", countryFocus: "Wales", sortOrder: 21 },
  { code: "scottish_general", label: "General Scottish", group: "UK & Ireland", countryFocus: "Scotland", sortOrder: 22 },
  { code: "glasgow", label: "Glasgow", group: "UK & Ireland", countryFocus: "Scotland", sortOrder: 23 },
  { code: "edinburgh", label: "Edinburgh", group: "UK & Ireland", countryFocus: "Scotland", sortOrder: 24 },
  { code: "highlands_scottish", label: "Highlands Scottish", group: "UK & Ireland", countryFocus: "Scotland", sortOrder: 25 },
  { code: "irish_general", label: "General Irish", group: "UK & Ireland", countryFocus: "Ireland", sortOrder: 26 },
  { code: "dublin", label: "Dublin", group: "UK & Ireland", countryFocus: "Ireland", sortOrder: 27 },
  { code: "northern_irish", label: "Northern Irish", group: "UK & Ireland", countryFocus: "Northern Ireland", sortOrder: 28 },
  { code: "cork", label: "Cork", group: "UK & Ireland", countryFocus: "Ireland", sortOrder: 29 },
  { code: "general_american", label: "General American", group: "North America", countryFocus: "United States", sortOrder: 30 },
  { code: "standard_american", label: "Standard American", group: "North America", countryFocus: "United States", sortOrder: 31 },
  { code: "new_york", label: "New York", group: "North America", countryFocus: "United States", sortOrder: 32 },
  { code: "boston", label: "Boston", group: "North America", countryFocus: "United States", sortOrder: 33 },
  { code: "southern_american", label: "Southern American", group: "North America", countryFocus: "United States", sortOrder: 34 },
  { code: "texan", label: "Texan", group: "North America", countryFocus: "United States", sortOrder: 35 },
  { code: "californian", label: "Californian", group: "North America", countryFocus: "United States", sortOrder: 36 },
  { code: "midwestern", label: "Midwestern American", group: "North America", countryFocus: "United States", sortOrder: 37 },
  { code: "african_american_vernacular", label: "African-American Vernacular", group: "North America", countryFocus: "United States", sortOrder: 38 },
  { code: "appalachian", label: "Appalachian", group: "North America", countryFocus: "United States", sortOrder: 39 },
  { code: "canadian_english", label: "Canadian English", group: "North America", countryFocus: "Canada", sortOrder: 40 },
  { code: "french_parisian", label: "Parisian French Accent", group: "Europe", countryFocus: "France", sortOrder: 41 },
  { code: "southern_french", label: "Southern French Accent", group: "Europe", countryFocus: "France", sortOrder: 42 },
  { code: "german", label: "German Accent", group: "Europe", countryFocus: "Germany", sortOrder: 43 },
  { code: "austrian", label: "Austrian Accent", group: "Europe", countryFocus: "Austria", sortOrder: 44 },
  { code: "swiss_german", label: "Swiss German Accent", group: "Europe", countryFocus: "Switzerland", sortOrder: 45 },
  { code: "italian", label: "Italian Accent", group: "Europe", countryFocus: "Italy", sortOrder: 46 },
  { code: "spanish_castilian", label: "Castilian Spanish Accent", group: "Europe", countryFocus: "Spain", sortOrder: 47 },
  { code: "spanish_latin_american", label: "Latin American Spanish Accent", group: "Latin America", countryFocus: "Multiple", sortOrder: 48 },
  { code: "portuguese_portugal", label: "European Portuguese Accent", group: "Europe", countryFocus: "Portugal", sortOrder: 49 },
  { code: "brazilian_portuguese", label: "Brazilian Portuguese Accent", group: "Latin America", countryFocus: "Brazil", sortOrder: 50 },
  { code: "dutch", label: "Dutch Accent", group: "Europe", countryFocus: "Netherlands", sortOrder: 51 },
  { code: "belgian_dutch", label: "Belgian Dutch / Flemish Accent", group: "Europe", countryFocus: "Belgium", sortOrder: 52 },
  { code: "belgian_french", label: "Belgian French Accent", group: "Europe", countryFocus: "Belgium", sortOrder: 53 },
  { code: "greek", label: "Greek Accent", group: "Europe", countryFocus: "Greece", sortOrder: 54 },
  { code: "polish", label: "Polish Accent", group: "Europe", countryFocus: "Poland", sortOrder: 55 },
  { code: "russian", label: "Russian Accent", group: "Europe / Eurasia", countryFocus: "Russia", sortOrder: 56 },
  { code: "ukrainian", label: "Ukrainian Accent", group: "Europe", countryFocus: "Ukraine", sortOrder: 57 },
  { code: "romanian", label: "Romanian Accent", group: "Europe", countryFocus: "Romania", sortOrder: 58 },
  { code: "hungarian", label: "Hungarian Accent", group: "Europe", countryFocus: "Hungary", sortOrder: 59 },
  { code: "turkish", label: "Turkish Accent", group: "Europe / Middle East", countryFocus: "T�rkiye", sortOrder: 60 },
  { code: "arabic_general", label: "General Arabic Accent", group: "Middle East / Africa", countryFocus: "Multiple", sortOrder: 61 },
  { code: "egyptian_arabic", label: "Egyptian Arabic Accent", group: "Middle East / Africa", countryFocus: "Egypt", sortOrder: 62 },
  { code: "levantine_arabic", label: "Levantine Arabic Accent", group: "Middle East / Africa", countryFocus: "Multiple", sortOrder: 63 },
  { code: "gulf_arabic", label: "Gulf Arabic Accent", group: "Middle East / Africa", countryFocus: "Multiple", sortOrder: 64 },
  { code: "israeli", label: "Israeli Accent", group: "Middle East / Africa", countryFocus: "Israel", sortOrder: 65 },
  { code: "persian_farsi", label: "Persian / Farsi Accent", group: "Middle East / Africa", countryFocus: "Iran", sortOrder: 66 },
  { code: "indian_general", label: "General Indian Accent", group: "South Asia", countryFocus: "India", sortOrder: 67 },
  { code: "hindi_belt", label: "Hindi Belt / North Indian Accent", group: "South Asia", countryFocus: "India", sortOrder: 68 },
  { code: "punjabi", label: "Punjabi Accent", group: "South Asia", countryFocus: "India / Pakistan", sortOrder: 69 },
  { code: "gujarati", label: "Gujarati Accent", group: "South Asia", countryFocus: "India", sortOrder: 70 },
  { code: "bengali", label: "Bengali Accent", group: "South Asia", countryFocus: "India / Bangladesh", sortOrder: 71 },
  { code: "tamil", label: "Tamil Accent", group: "South Asia", countryFocus: "India / Sri Lanka", sortOrder: 72 },
  { code: "telugu", label: "Telugu Accent", group: "South Asia", countryFocus: "India", sortOrder: 73 },
  { code: "malayalam", label: "Malayalam Accent", group: "South Asia", countryFocus: "India", sortOrder: 74 },
  { code: "pakistani_general", label: "General Pakistani Accent", group: "South Asia", countryFocus: "Pakistan", sortOrder: 75 },
  { code: "urdu", label: "Urdu Accent", group: "South Asia", countryFocus: "Pakistan", sortOrder: 76 },
  { code: "nepali", label: "Nepali Accent", group: "South Asia", countryFocus: "Nepal", sortOrder: 77 },
  { code: "sri_lankan", label: "Sri Lankan Accent", group: "South Asia", countryFocus: "Sri Lanka", sortOrder: 78 },
  { code: "nigerian_general", label: "General Nigerian Accent", group: "Africa", countryFocus: "Nigeria", sortOrder: 79 },
  { code: "yoruba_nigerian", label: "Yoruba-Influenced Nigerian Accent", group: "Africa", countryFocus: "Nigeria", sortOrder: 80 },
  { code: "igbo_nigerian", label: "Igbo-Influenced Nigerian Accent", group: "Africa", countryFocus: "Nigeria", sortOrder: 81 },
  { code: "hausa_nigerian", label: "Hausa-Influenced Nigerian Accent", group: "Africa", countryFocus: "Nigeria", sortOrder: 82 },
  { code: "ghanaian_general", label: "General Ghanaian Accent", group: "Africa", countryFocus: "Ghana", sortOrder: 83 },
  { code: "kenyan", label: "Kenyan Accent", group: "Africa", countryFocus: "Kenya", sortOrder: 84 },
  { code: "ugandan", label: "Ugandan Accent", group: "Africa", countryFocus: "Uganda", sortOrder: 85 },
  { code: "south_african_general", label: "General South African Accent", group: "Africa", countryFocus: "South Africa", sortOrder: 86 },
  { code: "afrikaans_influenced", label: "Afrikaans-Influenced Accent", group: "Africa", countryFocus: "South Africa", sortOrder: 87 },
  { code: "zimbabwean", label: "Zimbabwean Accent", group: "Africa", countryFocus: "Zimbabwe", sortOrder: 88 },
  { code: "ethiopian", label: "Ethiopian Accent", group: "Africa", countryFocus: "Ethiopia", sortOrder: 89 },
  { code: "somali", label: "Somali Accent", group: "Africa", countryFocus: "Somalia", sortOrder: 90 },
  { code: "jamaican", label: "Jamaican Accent", group: "Caribbean", countryFocus: "Jamaica", sortOrder: 91 },
  { code: "trinidadian", label: "Trinidadian Accent", group: "Caribbean", countryFocus: "Trinidad and Tobago", sortOrder: 92 },
  { code: "barbadian", label: "Barbadian / Bajan Accent", group: "Caribbean", countryFocus: "Barbados", sortOrder: 93 },
  { code: "haitian_french_creole", label: "Haitian French / Creole Accent", group: "Caribbean", countryFocus: "Haiti", sortOrder: 94 },
  { code: "australian_general", label: "General Australian Accent", group: "Oceania", countryFocus: "Australia", sortOrder: 95 },
  { code: "broad_australian", label: "Broad Australian Accent", group: "Oceania", countryFocus: "Australia", sortOrder: 96 },
  { code: "cultivated_australian", label: "Cultivated Australian Accent", group: "Oceania", countryFocus: "Australia", sortOrder: 97 },
  { code: "new_zealand", label: "New Zealand Accent", group: "Oceania", countryFocus: "New Zealand", sortOrder: 98 },
  { code: "south_east_asian_general", label: "General Southeast Asian Accent", group: "Southeast Asia", countryFocus: "Multiple", sortOrder: 99 },
  { code: "filipino", label: "Filipino Accent", group: "Southeast Asia", countryFocus: "Philippines", sortOrder: 100 },
  { code: "singaporean", label: "Singaporean Accent", group: "Southeast Asia", countryFocus: "Singapore", sortOrder: 101 },
  { code: "malaysian", label: "Malaysian Accent", group: "Southeast Asia", countryFocus: "Malaysia", sortOrder: 102 },
  { code: "thai", label: "Thai Accent", group: "Southeast Asia", countryFocus: "Thailand", sortOrder: 103 },
  { code: "vietnamese", label: "Vietnamese Accent", group: "Southeast Asia", countryFocus: "Vietnam", sortOrder: 104 },
  { code: "chinese_mandarin_influenced", label: "Mandarin-Influenced English Accent", group: "East Asia", countryFocus: "China", sortOrder: 105 },
  { code: "cantonese_influenced", label: "Cantonese-Influenced English Accent", group: "East Asia", countryFocus: "Hong Kong / China", sortOrder: 106 },
  { code: "japanese", label: "Japanese Accent", group: "East Asia", countryFocus: "Japan", sortOrder: 107 },
  { code: "korean", label: "Korean Accent", group: "East Asia", countryFocus: "Korea", sortOrder: 108 },
  { code: "neutral", label: "Neutral / International Neutral", group: "General", countryFocus: "Multiple", sortOrder: 109 },
  { code: "other", label: "Other", group: "Other", countryFocus: "Multiple", sortOrder: 110 },
];
export const MUSICAL_INSTRUMENTS: ReferenceItem[] = [
  { code: "vocals", label: "Vocals", group: "Voice", sortOrder: 1 },
  { code: "piano", label: "Piano", group: "Keyboard", sortOrder: 2 },
  { code: "keyboard", label: "Keyboard", group: "Keyboard", sortOrder: 3 },
  { code: "synthesizer", label: "Synthesizer", group: "Keyboard", sortOrder: 4 },
  { code: "organ", label: "Organ", group: "Keyboard", sortOrder: 5 },
  { code: "electric_guitar", label: "Electric Guitar", group: "Strings", sortOrder: 6 },
  { code: "acoustic_guitar", label: "Acoustic Guitar", group: "Strings", sortOrder: 7 },
  { code: "bass_guitar", label: "Bass Guitar", group: "Strings", sortOrder: 8 },
  { code: "classical_guitar", label: "Classical Guitar", group: "Strings", sortOrder: 9 },
  { code: "ukulele", label: "Ukulele", group: "Strings", sortOrder: 10 },
  { code: "harp", label: "Harp", group: "Strings", sortOrder: 11 },
  { code: "violin", label: "Violin", group: "Strings", sortOrder: 12 },
  { code: "viola", label: "Viola", group: "Strings", sortOrder: 13 },
  { code: "cello", label: "Cello", group: "Strings", sortOrder: 14 },
  { code: "double_bass", label: "Double Bass", group: "Strings", sortOrder: 15 },
  { code: "banjo", label: "Banjo", group: "Strings", sortOrder: 16 },
  { code: "mandolin", label: "Mandolin", group: "Strings", sortOrder: 17 },
  { code: "drums", label: "Drums", group: "Percussion", sortOrder: 18 },
  { code: "drum_kit", label: "Drum Kit", group: "Percussion", sortOrder: 19 },
  { code: "percussion", label: "Percussion", group: "Percussion", sortOrder: 20 },
  { code: "congas", label: "Congas", group: "Percussion", sortOrder: 21 },
  { code: "bongos", label: "Bongos", group: "Percussion", sortOrder: 22 },
  { code: "djembe", label: "Djembe", group: "Percussion", sortOrder: 23 },
  { code: "talking_drum", label: "Talking Drum (Gangan)", group: "Percussion", sortOrder: 24 },
  { code: "tambourine", label: "Tambourine", group: "Percussion", sortOrder: 25 },
  { code: "xylophone", label: "Xylophone", group: "Percussion", sortOrder: 26 },
  { code: "marimba", label: "Marimba", group: "Percussion", sortOrder: 27 },
  { code: "saxophone", label: "Saxophone", group: "Woodwind", sortOrder: 28 },
  { code: "clarinet", label: "Clarinet", group: "Woodwind", sortOrder: 29 },
  { code: "flute", label: "Flute", group: "Woodwind", sortOrder: 30 },
  { code: "piccolo", label: "Piccolo", group: "Woodwind", sortOrder: 31 },
  { code: "oboe", label: "Oboe", group: "Woodwind", sortOrder: 32 },
  { code: "bassoon", label: "Bassoon", group: "Woodwind", sortOrder: 33 },
  { code: "recorder", label: "Recorder", group: "Woodwind", sortOrder: 34 },
  { code: "trumpet", label: "Trumpet", group: "Brass", sortOrder: 35 },
  { code: "trombone", label: "Trombone", group: "Brass", sortOrder: 36 },
  { code: "french_horn", label: "French Horn", group: "Brass", sortOrder: 37 },
  { code: "tuba", label: "Tuba", group: "Brass", sortOrder: 38 },
  { code: "cornet", label: "Cornet", group: "Brass", sortOrder: 39 },
  { code: "euphonium", label: "Euphonium", group: "Brass", sortOrder: 40 },
  { code: "harmonica", label: "Harmonica", group: "Folk / Traditional", sortOrder: 41 },
  { code: "accordion", label: "Accordion", group: "Folk / Traditional", sortOrder: 42 },
  { code: "mouth_organ", label: "Mouth Organ", group: "Folk / Traditional", sortOrder: 43 },
  { code: "bagpipes", label: "Bagpipes", group: "Folk / Traditional", sortOrder: 44 },
  { code: "sitar", label: "Sitar", group: "World / Traditional", sortOrder: 45 },
  { code: "tabla", label: "Tabla", group: "World / Traditional", sortOrder: 46 },
  { code: "veena", label: "Veena", group: "World / Traditional", sortOrder: 47 },
  { code: "oud", label: "Oud", group: "World / Traditional", sortOrder: 48 },
  { code: "kora", label: "Kora", group: "World / Traditional", sortOrder: 49 },
  { code: "shekere", label: "Shekere", group: "World / Traditional", sortOrder: 50 },
  { code: "kalimba", label: "Kalimba", group: "World / Traditional", sortOrder: 51 },
  { code: "steel_pan", label: "Steel Pan", group: "World / Traditional", sortOrder: 52 },
  { code: "udu", label: "Udu", group: "World / Traditional", sortOrder: 53 },
  { code: "pan_flute", label: "Pan Flute", group: "World / Traditional", sortOrder: 54 },
  { code: "electronic_pad", label: "Electronic Pad", group: "Electronic / Production", sortOrder: 55 },
  { code: "drum_machine", label: "Drum Machine", group: "Electronic / Production", sortOrder: 56 },
  { code: "sampler", label: "Sampler", group: "Electronic / Production", sortOrder: 57 },
  { code: "midi_controller", label: "MIDI Controller", group: "Electronic / Production", sortOrder: 58 },
  { code: "turntables", label: "Turntables / DJ Decks", group: "Electronic / Production", sortOrder: 59 },
  { code: "dj_controller", label: "DJ Controller", group: "Electronic / Production", sortOrder: 60 },
  { code: "beat_machine", label: "Beat Machine", group: "Electronic / Production", sortOrder: 61 },
  { code: "music_production_software", label: "Music Production Software", group: "Electronic / Production", sortOrder: 62 },
  { code: "other", label: "Other", group: "Other", sortOrder: 63 },
];

export const DANCE_STYLES: ReferenceItem[] = [
  { code: "ballet", label: "Ballet", group: "Classical / Technical", sortOrder: 1 },
  { code: "pointe", label: "Pointe", group: "Classical / Technical", sortOrder: 2 },
  { code: "contemporary", label: "Contemporary", group: "Contemporary / Modern", sortOrder: 3 },
  { code: "lyrical", label: "Lyrical", group: "Contemporary / Modern", sortOrder: 4 },
  { code: "modern", label: "Modern", group: "Contemporary / Modern", sortOrder: 5 },
  { code: "jazz", label: "Jazz", group: "Theatre / Commercial", sortOrder: 6 },
  { code: "musical_theatre_dance", label: "Musical Theatre Dance", group: "Theatre / Commercial", sortOrder: 7 },
  { code: "commercial_dance", label: "Commercial Dance", group: "Theatre / Commercial", sortOrder: 8 },
  { code: "street_dance", label: "Street / Urban", group: "Street / Urban", sortOrder: 9 },
  { code: "hip_hop", label: "Hip Hop", group: "Street / Urban", sortOrder: 10 },
  { code: "locking", label: "Locking", group: "Street / Urban", sortOrder: 11 },
  { code: "popping", label: "Popping", group: "Street / Urban", sortOrder: 12 },
  { code: "breaking", label: "Breaking / Breakdance", group: "Street / Urban", sortOrder: 13 },
  { code: "krump", label: "Krump", group: "Street / Urban", sortOrder: 14 },
  { code: "house_dance", label: "House Dance", group: "Street / Urban", sortOrder: 15 },
  { code: "waacking", label: "Waacking", group: "Street / Urban", sortOrder: 16 },
  { code: "voguing", label: "Voguing", group: "Street / Urban", sortOrder: 17 },
  { code: "afro_dance", label: "Afro Dance", group: "African / Diaspora", sortOrder: 18 },
  { code: "afrobeats_dance", label: "Afrobeats Dance", group: "African / Diaspora", sortOrder: 19 },
  { code: "amapiano_dance", label: "Amapiano Dance", group: "African / Diaspora", sortOrder: 20 },
  { code: "azonto", label: "Azonto", group: "African / Diaspora", sortOrder: 21 },
  { code: "kuduro", label: "Kuduro", group: "African / Diaspora", sortOrder: 22 },
  { code: "traditional_african", label: "Traditional African Dance", group: "African / Diaspora", sortOrder: 23 },
  { code: "salsa", label: "Salsa", group: "Latin / Ballroom / Social", sortOrder: 24 },
  { code: "bachata", label: "Bachata", group: "Latin / Ballroom / Social", sortOrder: 25 },
  { code: "merengue", label: "Merengue", group: "Latin / Ballroom / Social", sortOrder: 26 },
  { code: "samba", label: "Samba", group: "Latin / Ballroom / Social", sortOrder: 27 },
  { code: "cha_cha", label: "Cha-Cha", group: "Latin / Ballroom / Social", sortOrder: 28 },
  { code: "rumba", label: "Rumba", group: "Latin / Ballroom / Social", sortOrder: 29 },
  { code: "paso_doble", label: "Paso Doble", group: "Latin / Ballroom / Social", sortOrder: 30 },
  { code: "jive", label: "Jive", group: "Latin / Ballroom / Social", sortOrder: 31 },
  { code: "tango", label: "Tango", group: "Latin / Ballroom / Social", sortOrder: 32 },
  { code: "ballroom", label: "Ballroom", group: "Latin / Ballroom / Social", sortOrder: 33 },
  { code: "waltz", label: "Waltz", group: "Latin / Ballroom / Social", sortOrder: 34 },
  { code: "foxtrot", label: "Foxtrot", group: "Latin / Ballroom / Social", sortOrder: 35 },
  { code: "quickstep", label: "Quickstep", group: "Latin / Ballroom / Social", sortOrder: 36 },
  { code: "tap", label: "Tap", group: "Classical / Technical", sortOrder: 37 },
  { code: "clog", label: "Clog Dance", group: "Folk / Traditional", sortOrder: 38 },
  { code: "irish_dance", label: "Irish Dance", group: "Folk / Traditional", sortOrder: 39 },
  { code: "ceilidh", label: "Ceilidh Dance", group: "Folk / Traditional", sortOrder: 40 },
  { code: "flamenco", label: "Flamenco", group: "Folk / Traditional", sortOrder: 41 },
  { code: "bollywood", label: "Bollywood", group: "South Asian", sortOrder: 42 },
  { code: "bhangra", label: "Bhangra", group: "South Asian", sortOrder: 43 },
  { code: "kathak", label: "Kathak", group: "South Asian", sortOrder: 44 },
  { code: "bharatanatyam", label: "Bharatanatyam", group: "South Asian", sortOrder: 45 },
  { code: "odissi", label: "Odissi", group: "South Asian", sortOrder: 46 },
  { code: "kuchipudi", label: "Kuchipudi", group: "South Asian", sortOrder: 47 },
  { code: "street_jazz", label: "Street Jazz", group: "Theatre / Commercial", sortOrder: 48 },
  { code: "heels", label: "Heels", group: "Theatre / Commercial", sortOrder: 49 },
  { code: "freestyle", label: "Freestyle", group: "General / Open Style", sortOrder: 50 },
  { code: "improvisation_dance", label: "Improvisation", group: "General / Open Style", sortOrder: 51 },
  { code: "acro_dance", label: "Acro Dance", group: "Speciality / Athletic", sortOrder: 52 },
  { code: "aerial_dance", label: "Aerial Dance", group: "Speciality / Athletic", sortOrder: 53 },
  { code: "cheer_dance", label: "Cheer Dance", group: "Speciality / Athletic", sortOrder: 54 },
  { code: "majorette", label: "Majorette", group: "Speciality / Athletic", sortOrder: 55 },
  { code: "partner_dance", label: "Partner Dance", group: "General / Open Style", sortOrder: 56 },
  { code: "cultural_fusion", label: "Cultural Fusion", group: "General / Open Style", sortOrder: 57 },
  { code: "experimental_dance", label: "Experimental Dance", group: "General / Open Style", sortOrder: 58 },
  { code: "other", label: "Other", group: "Other", sortOrder: 59 },
];


export const COUNTRIES = [
  "United Kingdom",
  "United States",
  "Ireland",
  "Scotland",
  "Wales",
  "France",
  "Germany",
  "Netherlands",
  "Belgium",
  "Spain",
  "Portugal",
  "Italy",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Poland",
  "Romania",
  "Ukraine",
  "Turkey",
  "Greece",
  "Russia",
  "Canada",
  "Australia",
  "New Zealand",
  "India",
  "Pakistan",
  "Bangladesh",
  "Sri Lanka",
  "Nepal",
  "China",
  "Japan",
  "South Korea",
  "Indonesia",
  "Malaysia",
  "Singapore",
  "Philippines",
  "Thailand",
  "Vietnam",
  "Brazil",
  "Mexico",
  "Argentina",
  "Jamaica",
  "Trinidad and Tobago",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Israel"
];
export const getReferenceOptions = (source: string): string[] => {
  switch (source) {
    case "countries":
      return COUNTRIES;
    case "music_genres":
      return MUSIC_GENRES.map((item) => item.label);
    case "languages":
      return LANGUAGES.map((item) => item.label);
    case "accents":
      return ACCENTS.map((item) => item.label);
    case "instruments":
      return MUSICAL_INSTRUMENTS.map((item) => item.label);
    case "dance_styles":
      return DANCE_STYLES.map((item) => item.label);
    case "opportunities_sought":
      return OPPORTUNITIES_SOUGHT_OPTIONS;
    default:
      return [];
  }
};





