export interface ReferenceItem {
  code: string;
  label: string;
  group: string;
  sortOrder: number;
  iso6391?: string | null;
  countryFocus?: string;
}

export const OPPORTUNITIES_SOUGHT_OPTIONS = [
  "Film",
  "TV",
  "Theatre",
  "Commercials",
  "Voiceover",
  "Modelling",
  "Live Events",
  "Brand Collaborations",
  "Content Creation",
  "Music Videos",
];

export const MUSIC_GENRES: ReferenceItem[] = [
  { code: "pop", label: "Pop", group: "Mainstream / Popular", sortOrder: 1 },
  { code: "afrobeats", label: "Afrobeats", group: "Mainstream / Popular", sortOrder: 2 },
  { code: "afro_pop", label: "Afro Pop", group: "Mainstream / Popular", sortOrder: 3 },
  { code: "rnb", label: "R&B", group: "Mainstream / Popular", sortOrder: 4 },
  { code: "soul", label: "Soul", group: "Mainstream / Popular", sortOrder: 5 },
  { code: "hip_hop", label: "Hip Hop", group: "Mainstream / Popular", sortOrder: 6 },
  { code: "rap", label: "Rap", group: "Mainstream / Popular", sortOrder: 7 },
  { code: "trap", label: "Trap", group: "Mainstream / Popular", sortOrder: 8 },
  { code: "dancehall", label: "Dancehall", group: "Mainstream / Popular", sortOrder: 9 },
  { code: "reggae", label: "Reggae", group: "Mainstream / Popular", sortOrder: 10 },
  { code: "amapiano", label: "Amapiano", group: "Mainstream / Popular", sortOrder: 11 },
  { code: "house", label: "House", group: "Mainstream / Popular", sortOrder: 12 },
  { code: "edm", label: "EDM", group: "Mainstream / Popular", sortOrder: 13 },
  { code: "electronic", label: "Electronic", group: "Mainstream / Popular", sortOrder: 14 },
  { code: "drum_and_bass", label: "Drum & Bass", group: "Mainstream / Popular", sortOrder: 15 },
  { code: "garage", label: "Garage", group: "Mainstream / Popular", sortOrder: 16 },
  { code: "uk_garage", label: "UK Garage", group: "Mainstream / Popular", sortOrder: 17 },
  { code: "grime", label: "Grime", group: "Mainstream / Popular", sortOrder: 18 },
  { code: "classical", label: "Classical", group: "Traditional / Classic", sortOrder: 19 },
  { code: "opera", label: "Opera", group: "Traditional / Classic", sortOrder: 20 },
  { code: "jazz", label: "Jazz", group: "Traditional / Classic", sortOrder: 21 },
  { code: "blues", label: "Blues", group: "Traditional / Classic", sortOrder: 22 },
  { code: "gospel", label: "Gospel", group: "Faith / Inspirational", sortOrder: 23 },
  { code: "contemporary_gospel", label: "Contemporary Gospel", group: "Faith / Inspirational", sortOrder: 24 },
  { code: "worship", label: "Worship", group: "Faith / Inspirational", sortOrder: 25 },
  { code: "hymns", label: "Hymns", group: "Faith / Inspirational", sortOrder: 26 },
  { code: "christian_contemporary", label: "Christian Contemporary", group: "Faith / Inspirational", sortOrder: 27 },
  { code: "praise", label: "Praise", group: "Faith / Inspirational", sortOrder: 28 },
  { code: "gospel_choir", label: "Gospel Choir", group: "Faith / Inspirational", sortOrder: 29 },
  { code: "inspirational", label: "Inspirational", group: "Faith / Inspirational", sortOrder: 30 },
  { code: "folk", label: "Folk", group: "Traditional / Classic", sortOrder: 31 },
  { code: "country", label: "Country", group: "Traditional / Classic", sortOrder: 32 },
  { code: "bluegrass", label: "Bluegrass", group: "Traditional / Classic", sortOrder: 33 },
  { code: "rock", label: "Rock", group: "Rock / Alternative", sortOrder: 34 },
  { code: "pop_rock", label: "Pop Rock", group: "Rock / Alternative", sortOrder: 35 },
  { code: "alternative_rock", label: "Alternative Rock", group: "Rock / Alternative", sortOrder: 36 },
  { code: "indie_rock", label: "Indie Rock", group: "Rock / Alternative", sortOrder: 37 },
  { code: "indie_pop", label: "Indie Pop", group: "Rock / Alternative", sortOrder: 38 },
  { code: "punk", label: "Punk", group: "Rock / Alternative", sortOrder: 39 },
  { code: "metal", label: "Metal", group: "Rock / Alternative", sortOrder: 40 },
  { code: "soft_rock", label: "Soft Rock", group: "Rock / Alternative", sortOrder: 41 },
  { code: "highlife", label: "Highlife", group: "African / World / Cultural", sortOrder: 42 },
  { code: "fuji", label: "Fuji", group: "African / World / Cultural", sortOrder: 43 },
  { code: "juju", label: "Juju", group: "African / World / Cultural", sortOrder: 44 },
  { code: "apala", label: "Apala", group: "African / World / Cultural", sortOrder: 45 },
  { code: "afro_fusion", label: "Afro Fusion", group: "African / World / Cultural", sortOrder: 46 },
  { code: "afro_soul", label: "Afro Soul", group: "African / World / Cultural", sortOrder: 47 },
  { code: "afro_jazz", label: "Afro Jazz", group: "African / World / Cultural", sortOrder: 48 },
  { code: "world_music", label: "World Music", group: "African / World / Cultural", sortOrder: 49 },
  { code: "traditional_cultural", label: "Traditional / Cultural", group: "African / World / Cultural", sortOrder: 50 },
  { code: "latin", label: "Latin", group: "Latin / Global", sortOrder: 51 },
  { code: "salsa", label: "Salsa", group: "Latin / Global", sortOrder: 52 },
  { code: "reggaeton", label: "Reggaeton", group: "Latin / Global", sortOrder: 53 },
  { code: "bachata", label: "Bachata", group: "Latin / Global", sortOrder: 54 },
  { code: "samba", label: "Samba", group: "Latin / Global", sortOrder: 55 },
  { code: "bossa_nova", label: "Bossa Nova", group: "Latin / Global", sortOrder: 56 },
  { code: "musical_theatre", label: "Musical Theatre", group: "Performance / Screen / Theatre", sortOrder: 57 },
  { code: "soundtrack_film_music", label: "Soundtrack / Film Music", group: "Performance / Screen / Theatre", sortOrder: 58 },
  { code: "spoken_word", label: "Spoken Word", group: "Performance / Screen / Theatre", sortOrder: 59 },
  { code: "childrens_music", label: "Children's Music", group: "Performance / Screen / Theatre", sortOrder: 60 },
  { code: "lo_fi", label: "Lo-fi", group: "Chill / Lifestyle / Modern", sortOrder: 61 },
  { code: "acoustic", label: "Acoustic", group: "Chill / Lifestyle / Modern", sortOrder: 62 },
  { code: "easy_listening", label: "Easy Listening", group: "Chill / Lifestyle / Modern", sortOrder: 63 },
  { code: "chillout", label: "Chillout", group: "Chill / Lifestyle / Modern", sortOrder: 64 },
  { code: "ambient", label: "Ambient", group: "Chill / Lifestyle / Modern", sortOrder: 65 },
  { code: "neo_soul", label: "Neo Soul", group: "Chill / Lifestyle / Modern", sortOrder: 66 },
  { code: "funk", label: "Funk", group: "Chill / Lifestyle / Modern", sortOrder: 67 },
  { code: "disco", label: "Disco", group: "Chill / Lifestyle / Modern", sortOrder: 68 },
  { code: "experimental", label: "Experimental", group: "Other / Specialist", sortOrder: 69 },
  { code: "instrumental", label: "Instrumental", group: "Other / Specialist", sortOrder: 70 },
  { code: "fusion", label: "Fusion", group: "Other / Specialist", sortOrder: 71 },
  { code: "cross_genre", label: "Cross-Genre", group: "Other / Specialist", sortOrder: 72 },
  { code: "other", label: "Other", group: "Other / Specialist", sortOrder: 73 },
];
export const LANGUAGES: ReferenceItem[] = [
  { code: "english", label: "English", group: "International / Major", iso6391: "en", sortOrder: 1 },
  { code: "french", label: "French", group: "International / Major", iso6391: "fr", sortOrder: 2 },
  { code: "spanish", label: "Spanish", group: "International / Major", iso6391: "es", sortOrder: 3 },
  { code: "portuguese", label: "Portuguese", group: "International / Major", iso6391: "pt", sortOrder: 4 },
  { code: "german", label: "German", group: "International / Major", iso6391: "de", sortOrder: 5 },
  { code: "italian", label: "Italian", group: "International / Major", iso6391: "it", sortOrder: 6 },
  { code: "dutch", label: "Dutch", group: "International / Major", iso6391: "nl", sortOrder: 7 },
  { code: "arabic", label: "Arabic", group: "International / Major", iso6391: "ar", sortOrder: 8 },
  { code: "mandarin_chinese", label: "Mandarin Chinese", group: "International / Major", iso6391: "zh", sortOrder: 9 },
  { code: "cantonese", label: "Cantonese", group: "International / Major", iso6391: null, sortOrder: 10 },
  { code: "japanese", label: "Japanese", group: "International / Major", iso6391: "ja", sortOrder: 11 },
  { code: "korean", label: "Korean", group: "International / Major", iso6391: "ko", sortOrder: 12 },
  { code: "hindi", label: "Hindi", group: "International / Major", iso6391: "hi", sortOrder: 13 },
  { code: "urdu", label: "Urdu", group: "International / Major", iso6391: "ur", sortOrder: 14 },
  { code: "russian", label: "Russian", group: "International / Major", iso6391: "ru", sortOrder: 15 },
  { code: "ukrainian", label: "Ukrainian", group: "International / Major", iso6391: "uk", sortOrder: 16 },
  { code: "turkish", label: "Turkish", group: "International / Major", iso6391: "tr", sortOrder: 17 },
  { code: "greek", label: "Greek", group: "International / Major", iso6391: "el", sortOrder: 18 },
  { code: "swedish", label: "Swedish", group: "European", iso6391: "sv", sortOrder: 19 },
  { code: "norwegian", label: "Norwegian", group: "European", iso6391: "no", sortOrder: 20 },
  { code: "danish", label: "Danish", group: "European", iso6391: "da", sortOrder: 21 },
  { code: "finnish", label: "Finnish", group: "European", iso6391: "fi", sortOrder: 22 },
  { code: "polish", label: "Polish", group: "European", iso6391: "pl", sortOrder: 23 },
  { code: "romanian", label: "Romanian", group: "European", iso6391: "ro", sortOrder: 24 },
  { code: "hungarian", label: "Hungarian", group: "European", iso6391: "hu", sortOrder: 25 },
  { code: "czech", label: "Czech", group: "European", iso6391: "cs", sortOrder: 26 },
  { code: "slovak", label: "Slovak", group: "European", iso6391: "sk", sortOrder: 27 },
  { code: "bulgarian", label: "Bulgarian", group: "European", iso6391: "bg", sortOrder: 28 },
  { code: "croatian", label: "Croatian", group: "European", iso6391: "hr", sortOrder: 29 },
  { code: "serbian", label: "Serbian", group: "European", iso6391: "sr", sortOrder: 30 },
  { code: "slovenian", label: "Slovenian", group: "European", iso6391: "sl", sortOrder: 31 },
  { code: "albanian", label: "Albanian", group: "European", iso6391: "sq", sortOrder: 32 },
  { code: "lithuanian", label: "Lithuanian", group: "European", iso6391: "lt", sortOrder: 33 },
  { code: "latvian", label: "Latvian", group: "European", iso6391: "lv", sortOrder: 34 },
  { code: "estonian", label: "Estonian", group: "European", iso6391: "et", sortOrder: 35 },
  { code: "hebrew", label: "Hebrew", group: "Middle East / Africa", iso6391: "he", sortOrder: 36 },
  { code: "persian_farsi", label: "Persian / Farsi", group: "Middle East / Africa", iso6391: "fa", sortOrder: 37 },
  { code: "amharic", label: "Amharic", group: "Middle East / Africa", iso6391: "am", sortOrder: 38 },
  { code: "swahili", label: "Swahili", group: "African", iso6391: "sw", sortOrder: 39 },
  { code: "hausa", label: "Hausa", group: "African", iso6391: null, sortOrder: 40 },
  { code: "yoruba", label: "Yoruba", group: "African", iso6391: null, sortOrder: 41 },
  { code: "igbo", label: "Igbo", group: "African", iso6391: null, sortOrder: 42 },
  { code: "pidgin_english", label: "Pidgin English", group: "African", iso6391: null, sortOrder: 43 },
  { code: "zulu", label: "Zulu", group: "African", iso6391: "zu", sortOrder: 44 },
  { code: "xhosa", label: "Xhosa", group: "African", iso6391: "xh", sortOrder: 45 },
  { code: "afrikaans", label: "Afrikaans", group: "African", iso6391: "af", sortOrder: 46 },
  { code: "twi", label: "Twi", group: "African", iso6391: null, sortOrder: 47 },
  { code: "ga", label: "Ga", group: "African", iso6391: null, sortOrder: 48 },
  { code: "edo", label: "Edo", group: "African", iso6391: null, sortOrder: 49 },
  { code: "efik", label: "Efik", group: "African", iso6391: null, sortOrder: 50 },
  { code: "ibibio", label: "Ibibio", group: "African", iso6391: null, sortOrder: 51 },
  { code: "bengali", label: "Bengali", group: "South Asian", iso6391: "bn", sortOrder: 52 },
  { code: "punjabi", label: "Punjabi", group: "South Asian", iso6391: "pa", sortOrder: 53 },
  { code: "tamil", label: "Tamil", group: "South Asian", iso6391: "ta", sortOrder: 54 },
  { code: "telugu", label: "Telugu", group: "South Asian", iso6391: "te", sortOrder: 55 },
  { code: "malayalam", label: "Malayalam", group: "South Asian", iso6391: "ml", sortOrder: 56 },
  { code: "gujarati", label: "Gujarati", group: "South Asian", iso6391: "gu", sortOrder: 57 },
  { code: "marathi", label: "Marathi", group: "South Asian", iso6391: "mr", sortOrder: 58 },
  { code: "nepali", label: "Nepali", group: "South Asian", iso6391: "ne", sortOrder: 59 },
  { code: "sinhala", label: "Sinhala", group: "South Asian", iso6391: "si", sortOrder: 60 },
  { code: "thai", label: "Thai", group: "Southeast Asian", iso6391: "th", sortOrder: 61 },
  { code: "vietnamese", label: "Vietnamese", group: "Southeast Asian", iso6391: "vi", sortOrder: 62 },
  { code: "indonesian", label: "Indonesian", group: "Southeast Asian", iso6391: "id", sortOrder: 63 },
  { code: "malay", label: "Malay", group: "Southeast Asian", iso6391: "ms", sortOrder: 64 },
  { code: "tagalog", label: "Tagalog", group: "Southeast Asian", iso6391: "tl", sortOrder: 65 },
  { code: "filipino", label: "Filipino", group: "Southeast Asian", iso6391: null, sortOrder: 66 },
  { code: "burmese", label: "Burmese", group: "Southeast Asian", iso6391: "my", sortOrder: 67 },
  { code: "khmer", label: "Khmer", group: "Southeast Asian", iso6391: "km", sortOrder: 68 },
  { code: "lao", label: "Lao", group: "Southeast Asian", iso6391: "lo", sortOrder: 69 },
  { code: "somali", label: "Somali", group: "African", iso6391: "so", sortOrder: 70 },
  { code: "wolof", label: "Wolof", group: "African", iso6391: null, sortOrder: 71 },
  { code: "lingala", label: "Lingala", group: "African", iso6391: null, sortOrder: 72 },
  { code: "kinyarwanda", label: "Kinyarwanda", group: "African", iso6391: "rw", sortOrder: 73 },
  { code: "luganda", label: "Luganda", group: "African", iso6391: "lg", sortOrder: 74 },
  { code: "shona", label: "Shona", group: "African", iso6391: "sn", sortOrder: 75 },
  { code: "other", label: "Other", group: "Other", iso6391: null, sortOrder: 76 },
];
export const ACCENTS: ReferenceItem[] = [
  { code: "british_rp", label: "British RP / Received Pronunciation", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 1 },
  { code: "standard_british", label: "Standard British", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 2 },
  { code: "london", label: "London", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 3 },
  { code: "cockney", label: "Cockney", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 4 },
  { code: "essex", label: "Essex", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 5 },
  { code: "estuary_english", label: "Estuary English", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 6 },
  { code: "multicutural_london_english", label: "Multicultural London English", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 7 },
  { code: "southern_english", label: "Southern English", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 8 },
  { code: "northern_english", label: "Northern English", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 9 },
  { code: "yorkshire", label: "Yorkshire", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 10 },
  { code: "lancashire", label: "Lancashire", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 11 },
  { code: "geordie", label: "Geordie", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 12 },
  { code: "scouse", label: "Scouse", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 13 },
  { code: "mancunian", label: "Mancunian", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 14 },
  { code: "west_midlands", label: "West Midlands", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 15 },
  { code: "birmingham_brummie", label: "Birmingham / Brummie", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 16 },
  { code: "east_midlands", label: "East Midlands", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 17 },
  { code: "west_country", label: "West Country", group: "UK & Ireland", countryFocus: "United Kingdom", sortOrder: 18 },
  { code: "welsh", label: "Welsh", group: "UK & Ireland", countryFocus: "Wales", sortOrder: 19 },
  { code: "cardiff", label: "Cardiff / South Welsh", group: "UK & Ireland", countryFocus: "Wales", sortOrder: 20 },
  { code: "valleys_welsh", label: "Valleys Welsh", group: "UK & Ireland", countryFocus: "Wales", sortOrder: 21 },
  { code: "scottish_general", label: "General Scottish", group: "UK & Ireland", countryFocus: "Scotland", sortOrder: 22 },
  { code: "glasgow", label: "Glasgow", group: "UK & Ireland", countryFocus: "Scotland", sortOrder: 23 },
  { code: "edinburgh", label: "Edinburgh", group: "UK & Ireland", countryFocus: "Scotland", sortOrder: 24 },
  { code: "highlands_scottish", label: "Highlands Scottish", group: "UK & Ireland", countryFocus: "Scotland", sortOrder: 25 },
  { code: "irish_general", label: "General Irish", group: "UK & Ireland", countryFocus: "Ireland", sortOrder: 26 },
  { code: "dublin", label: "Dublin", group: "UK & Ireland", countryFocus: "Ireland", sortOrder: 27 },
  { code: "northern_irish", label: "Northern Irish", group: "UK & Ireland", countryFocus: "Northern Ireland", sortOrder: 28 },
  { code: "cork", label: "Cork", group: "UK & Ireland", countryFocus: "Ireland", sortOrder: 29 },
  { code: "general_american", label: "General American", group: "North America", countryFocus: "United States", sortOrder: 30 },
  { code: "standard_american", label: "Standard American", group: "North America", countryFocus: "United States", sortOrder: 31 },
  { code: "new_york", label: "New York", group: "North America", countryFocus: "United States", sortOrder: 32 },
  { code: "boston", label: "Boston", group: "North America", countryFocus: "United States", sortOrder: 33 },
  { code: "southern_american", label: "Southern American", group: "North America", countryFocus: "United States", sortOrder: 34 },
  { code: "texan", label: "Texan", group: "North America", countryFocus: "United States", sortOrder: 35 },
  { code: "californian", label: "Californian", group: "North America", countryFocus: "United States", sortOrder: 36 },
  { code: "midwestern", label: "Midwestern American", group: "North America", countryFocus: "United States", sortOrder: 37 },
  { code: "african_american_vernacular", label: "African-American Vernacular", group: "North America", countryFocus: "United States", sortOrder: 38 },
  { code: "appalachian", label: "Appalachian", group: "North America", countryFocus: "United States", sortOrder: 39 },
  { code: "canadian_english", label: "Canadian English", group: "North America", countryFocus: "Canada", sortOrder: 40 },
  { code: "french_parisian", label: "Parisian French Accent", group: "Europe", countryFocus: "France", sortOrder: 41 },
  { code: "southern_french", label: "Southern French Accent", group: "Europe", countryFocus: "France", sortOrder: 42 },
  { code: "german", label: "German Accent", group: "Europe", countryFocus: "Germany", sortOrder: 43 },
  { code: "austrian", label: "Austrian Accent", group: "Europe", countryFocus: "Austria", sortOrder: 44 },
  { code: "swiss_german", label: "Swiss German Accent", group: "Europe", countryFocus: "Switzerland", sortOrder: 45 },
  { code: "italian", label: "Italian Accent", group: "Europe", countryFocus: "Italy", sortOrder: 46 },
  { code: "spanish_castilian", label: "Castilian Spanish Accent", group: "Europe", countryFocus: "Spain", sortOrder: 47 },
  { code: "spanish_latin_american", label: "Latin American Spanish Accent", group: "Latin America", countryFocus: "Multiple", sortOrder: 48 },
  { code: "portuguese_portugal", label: "European Portuguese Accent", group: "Europe", countryFocus: "Portugal", sortOrder: 49 },
  { code: "brazilian_portuguese", label: "Brazilian Portuguese Accent", group: "Latin America", countryFocus: "Brazil", sortOrder: 50 },
  { code: "dutch", label: "Dutch Accent", group: "Europe", countryFocus: "Netherlands", sortOrder: 51 },
  { code: "belgian_dutch", label: "Belgian Dutch / Flemish Accent", group: "Europe", countryFocus: "Belgium", sortOrder: 52 },
  { code: "belgian_french", label: "Belgian French Accent", group: "Europe", countryFocus: "Belgium", sortOrder: 53 },
  { code: "greek", label: "Greek Accent", group: "Europe", countryFocus: "Greece", sortOrder: 54 },
  { code: "polish", label: "Polish Accent", group: "Europe", countryFocus: "Poland", sortOrder: 55 },
